models:
  SingaporeEnglish_0519NNET3: 1  
  SingaporeCS_0519NNET3: 3
  SingaporeMandarin_0519NNET3: 1
  
image:
  repository: kalditest.azurecr.io/kalditestscaled
  tag: latest
  pullPolicy: Always
  pullSecrets: azure-cr-secret

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 8080
  resourceGroup: kaldi-test
  loadBalancerIP: 52.148.116.121
  enablehttps: false

commands:
  master:
    - '"/home/appuser/opt/tini"' 
    - '"--"'
    - '"/home/appuser/opt/start_master.sh"'
  worker:
  # see _helpers.tpl on how full command constructed
    pre:
      - '"/home/appuser/opt/tini"' 
      - '"--"'
      - '"/home/appuser/opt/start_worker.sh"'
fileshare:
  secretName: models-files-secret
  shareName: online-models

